// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg3ptGCmNcQXP5uzDPy2hW8F9NtUkPmIo',
    appId: '1:110756724009:web:9054fa48e55acc89214b38',
    messagingSenderId: '110756724009',
    projectId: 'manzon-fc55b',
    authDomain: 'manzon-fc55b.firebaseapp.com',
    storageBucket: 'manzon-fc55b.appspot.com',
    measurementId: 'G-35HYR34PQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHaLAypLw5EGI0dQep0GCYDG_7MVSbygg',
    appId: '1:110756724009:android:9486ddf1d2b24df2214b38',
    messagingSenderId: '110756724009',
    projectId: 'manzon-fc55b',
    storageBucket: 'manzon-fc55b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyU3F_3PT1R6FyBLbe0sCdbyZBJpSwiY',
    appId: '1:110756724009:ios:158bd09226e7d893214b38',
    messagingSenderId: '110756724009',
    projectId: 'manzon-fc55b',
    storageBucket: 'manzon-fc55b.appspot.com',
    iosBundleId: 'com.example.manzon',
  );
}
